site_name: Reduce
site_description: 前端组件化打包方案
site_url: https://github.com/reducejs/reduce-web-component/
repo_url: https://github.com/reducejs/reducejs-handbook/
remote_branch: master
remote_name: site
docs_dir: '.'
pages:
  - Home: index.md
  - 快速入门:
    - Reduce是什么: quick-start/what-is-reduce.md
    - 基本使用: quick-start/getting-started.md
  - 教程:
    - 实例: tutorials/examples.md
    - 组件规范: tutorials/component.md
    - 打包策略: tutorials/how-to-bundle.md
    - 插件: tutorials/plugin.md
    - Transform: tutorials/transform.md
    - 定制PostCSS: tutorials/postcss.md
    - 热替换: tutorials/hot-module-replacement.md
  - API:
    - 配置: api/configure.md
    - 命令行: api/commond-line.md
    - Node.js: api/nodejs.md
  - 指南:
    - CSS命名空间: guides/css-namespace.md
    - 自动拼图: guides/sprite.md
    - React项目: guides/react.md
theme: readthedocs
extra_css:
  - css/extra-readthedocs.css
#theme_dir: 'themes'
